<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        Country::factory()
            ->createMany([
                ['name' => 'Afganistan', 'code' => 'AF'],
                ['name' => 'Albánsko', 'code' => 'AL'],
                ['name' => 'Alžírsko', 'code' => 'DZ'],
                ['name' => 'Andorra', 'code' => 'AD'],
                ['name' => 'Angola', 'code' => 'AO'],
                ['name' => 'Antigua a Barbuda', 'code' => 'AG'],
                ['name' => 'Argentína', 'code' => 'AR'],
                ['name' => 'Arménsko', 'code' => 'AM'],
                ['name' => 'Austrália', 'code' => 'AU'],
                ['name' => 'Azerbajdžan', 'code' => 'AZ'],
                ['name' => 'Bahamy', 'code' => 'BS'],
                ['name' => 'Bahrajn', 'code' => 'BH'],
                ['name' => 'Bangladéš', 'code' => 'BD'],
                ['name' => 'Barbados', 'code' => 'BB'],
                ['name' => 'Belgicko', 'code' => 'BE'],
                ['name' => 'Belize', 'code' => 'BZ'],
                ['name' => 'Benin', 'code' => 'BJ'],
                ['name' => 'Bhután', 'code' => 'BT'],
                ['name' => 'Bielorusko', 'code' => 'BY'],
                ['name' => 'Bolívia', 'code' => 'BO'],
                ['name' => 'Bosna a Hercegovina', 'code' => 'BA'],
                ['name' => 'Botswana', 'code' => 'BW'],
                ['name' => 'Brazília', 'code' => 'BR'],
                ['name' => 'Brunej', 'code' => 'BN'],
                ['name' => 'Bulharsko', 'code' => 'BG'],
                ['name' => 'Burkina Faso', 'code' => 'BF'],
                ['name' => 'Burundi', 'code' => 'BI'],
                ['name' => 'Čad', 'code' => 'TD'],
                ['name' => 'Česko', 'code' => 'CZ'],
                ['name' => 'Chorvátsko', 'code' => 'HR'],
                ['name' => 'Čierna Hora', 'code' => 'ME'],
                ['name' => 'Čile', 'code' => 'CL'],
                ['name' => 'Čína', 'code' => 'CN'],
                ['name' => 'Cyprus', 'code' => 'CY'],
                ['name' => 'Dánsko', 'code' => 'DK'],
                ['name' => 'Dominika', 'code' => 'DM'],
                ['name' => 'Dominikánska republika', 'code' => 'DO'],
                ['name' => 'Džibutsko', 'code' => 'DJ'],
                ['name' => 'Egypt', 'code' => 'EG'],
                ['name' => 'Ekvádor', 'code' => 'EC'],
                ['name' => 'Eritrea', 'code' => 'ER'],
                ['name' => 'Estónsko', 'code' => 'EE'],
                ['name' => 'Etiópia', 'code' => 'ET'],
                ['name' => 'Fidži', 'code' => 'FJ'],
                ['name' => 'Filipíny', 'code' => 'PH'],
                ['name' => 'Fínsko', 'code' => 'FI'],
                ['name' => 'Francúzsko', 'code' => 'FR'],
                ['name' => 'Gabon', 'code' => 'GA'],
                ['name' => 'Gambia', 'code' => 'GM'],
                ['name' => 'Ghana', 'code' => 'GH'],
                ['name' => 'Grécko', 'code' => 'GR'],
                ['name' => 'Grenada', 'code' => 'GD'],
                ['name' => 'Gruzínsko', 'code' => 'GE'],
                ['name' => 'Guatemala', 'code' => 'GT'],
                ['name' => 'Guinea-Bissau', 'code' => 'GW'],
                ['name' => 'Guinea', 'code' => 'GN'],
                ['name' => 'Guyana', 'code' => 'GY'],
                ['name' => 'Haiti', 'code' => 'HT'],
                ['name' => 'Holandsko', 'code' => 'NL'],
                ['name' => 'Honduras', 'code' => 'HN'],
                ['name' => 'India', 'code' => 'IN'],
                ['name' => 'Indonézia', 'code' => 'ID'],
                ['name' => 'Irak', 'code' => 'IQ'],
                ['name' => 'Irán', 'code' => 'IR'],
                ['name' => 'Írsko', 'code' => 'IE'],
                ['name' => 'Island', 'code' => 'IS'],
                ['name' => 'Izrael', 'code' => 'IL'],
                ['name' => 'Jamajka', 'code' => 'JM'],
                ['name' => 'Japonsko', 'code' => 'JP'],
                ['name' => 'Jemen', 'code' => 'YE'],
                ['name' => 'Jordánsko', 'code' => 'JO'],
                ['name' => 'Južná Afrika', 'code' => 'ZA'],
                ['name' => 'Južná Kórea', 'code' => 'KR'],
                ['name' => 'Južný Sudán', 'code' => 'SS'],
                ['name' => 'Kambodža', 'code' => 'KH'],
                ['name' => 'Kamerun', 'code' => 'CM'],
                ['name' => 'Kanada', 'code' => 'CA'],
                ['name' => 'Kapverdy', 'code' => 'CV'],
                ['name' => 'Katar', 'code' => 'QA'],
                ['name' => 'Kazachstan', 'code' => 'KZ'],
                ['name' => 'Keňa', 'code' => 'KE'],
                ['name' => 'Kirgisko', 'code' => 'KG'],
                ['name' => 'Kiribati', 'code' => 'KI'],
                ['name' => 'Kolumbia', 'code' => 'CO'],
                ['name' => 'Komory', 'code' => 'KM'],
                ['name' => 'Konžská demokratická republika', 'code' => 'CD'],
                ['name' => 'Konžská republika', 'code' => 'CG'],
                ['name' => 'Kostarika', 'code' => 'CR'],
                ['name' => 'Kuba', 'code' => 'CU'],
                ['name' => 'Kuvajt', 'code' => 'KW'],
                ['name' => 'Laos', 'code' => 'LA'],
                ['name' => 'Lesotho', 'code' => 'LS'],
                ['name' => 'Libanon', 'code' => 'LB'],
                ['name' => 'Libéria', 'code' => 'LR'],
                ['name' => 'Líbya', 'code' => 'LY'],
                ['name' => 'Lichtenštajnsko', 'code' => 'LI'],
                ['name' => 'Litva', 'code' => 'LT'],
                ['name' => 'Lotyšsko', 'code' => 'LV'],
                ['name' => 'Luxembursko', 'code' => 'LU'],
                ['name' => 'Madagaskar', 'code' => 'MG'],
                ['name' => 'Maďarsko', 'code' => 'HU'],
                ['name' => 'Malajzia', 'code' => 'MY'],
                ['name' => 'Malawi', 'code' => 'MW'],
                ['name' => 'Maldivy', 'code' => 'MV'],
                ['name' => 'Mali', 'code' => 'ML'],
                ['name' => 'Malta', 'code' => 'MT'],
                ['name' => 'Maroko', 'code' => 'MA'],
                ['name' => 'Marshallove ostrovy', 'code' => 'MH'],
                ['name' => 'Maurícius', 'code' => 'MU'],
                ['name' => 'Mauritánia', 'code' => 'MR'],
                ['name' => 'Mexiko', 'code' => 'MX'],
                ['name' => 'Mikronézia', 'code' => 'FM'],
                ['name' => 'Mjanmarsko', 'code' => 'MM'],
                ['name' => 'Moldavsko', 'code' => 'MD'],
                ['name' => 'Monako', 'code' => 'MC'],
                ['name' => 'Mongolsko', 'code' => 'MN'],
                ['name' => 'Mozambik', 'code' => 'MZ'],
                ['name' => 'Namíbia', 'code' => 'NA'],
                ['name' => 'Nauru', 'code' => 'NR'],
                ['name' => 'Nemecko', 'code' => 'DE'],
                ['name' => 'Nepál', 'code' => 'NP'],
                ['name' => 'Niger', 'code' => 'NE'],
                ['name' => 'Nigéria', 'code' => 'NG'],
                ['name' => 'Nikaragua', 'code' => 'NI'],
                ['name' => 'Nórsko', 'code' => 'NO'],
                ['name' => 'Nový Zéland', 'code' => 'NZ'],
                ['name' => 'Omán', 'code' => 'OM'],
                ['name' => 'Pakistán', 'code' => 'PK'],
                ['name' => 'Palau', 'code' => 'PW'],
                ['name' => 'Palestína', 'code' => 'PS'],
                ['name' => 'Panama', 'code' => 'PA'],
                ['name' => 'Papua-Nová Guinea', 'code' => 'PG'],
                ['name' => 'Paraguaj', 'code' => 'PY'],
                ['name' => 'Peru', 'code' => 'PE'],
                ['name' => 'Pobrežie slonoviny', 'code' => 'CI'],
                ['name' => 'Poľsko', 'code' => 'PL'],
                ['name' => 'Portugalsko', 'code' => 'PT'],
                ['name' => 'Rakúsko', 'code' => 'AT'],
                ['name' => 'Rovníková Guinea', 'code' => 'GQ'],
                ['name' => 'Rumunsko', 'code' => 'RO'],
                ['name' => 'Rusko', 'code' => 'RU'],
                ['name' => 'Rwanda', 'code' => 'RW'],
                ['name' => 'Šalamúnove ostrovy', 'code' => 'SB'],
                ['name' => 'Salvádor', 'code' => 'SV'],
                ['name' => 'Samoa', 'code' => 'WS'],
                ['name' => 'San Maríno', 'code' => 'SM'],
                ['name' => 'Saudská Arábia', 'code' => 'SA'],
                ['name' => 'Senegal', 'code' => 'SN'],
                ['name' => 'Severná Kórea', 'code' => 'KP'],
                ['name' => 'Severné Macedónsko', 'code' => 'MK'],
                ['name' => 'Seychely', 'code' => 'SC'],
                ['name' => 'Sierra Leone', 'code' => 'SL'],
                ['name' => 'Singapur', 'code' => 'SG'],
                ['name' => 'Slovensko', 'code' => 'SK'],
                ['name' => 'Slovinsko', 'code' => 'SI'],
                ['name' => 'Somálsko', 'code' => 'SO'],
                ['name' => 'Španielsko', 'code' => 'ES'],
                ['name' => 'Spojené arabské emiráty', 'code' => 'AE'],
                ['name' => 'Spojené kráľovstvo', 'code' => 'GB'],
                ['name' => 'Spojené štáty americké', 'code' => 'US'],
                ['name' => 'Srbsko', 'code' => 'RS'],
                ['name' => 'Srí Lanka', 'code' => 'LK'],
                ['name' => 'Stredoafrická republika', 'code' => 'CF'],
                ['name' => 'Sudán', 'code' => 'SD'],
                ['name' => 'Surinam', 'code' => 'SR'],
                ['name' => 'Švajčiarsko', 'code' => 'CH'],
                ['name' => 'Svätá Lucia', 'code' => 'LC'],
                ['name' => 'Svätý Krištof a Nevis', 'code' => 'KN'],
                ['name' => 'Svätý Tomáš a Princov ostrov', 'code' => 'ST'],
                ['name' => 'Svätý Vincent a Grenadíny', 'code' => 'VC'],
                ['name' => 'Svazijsko', 'code' => 'SZ'],
                ['name' => 'Švédsko', 'code' => 'SE'],
                ['name' => 'Sýria', 'code' => 'SY'],
                ['name' => 'Tadžikistan', 'code' => 'TJ'],
                ['name' => 'Taliansko', 'code' => 'IT'],
                ['name' => 'Tanzánia', 'code' => 'TZ'],
                ['name' => 'Thajsko', 'code' => 'TH'],
                ['name' => 'Togo', 'code' => 'TG'],
                ['name' => 'Tonga', 'code' => 'TO'],
                ['name' => 'Trinidad a Tobago', 'code' => 'TT'],
                ['name' => 'Tunisko', 'code' => 'TN'],
                ['name' => 'Turecko', 'code' => 'TR'],
                ['name' => 'Turkménsko', 'code' => 'TM'],
                ['name' => 'Tuvalu', 'code' => 'TV'],
                ['name' => 'Uganda', 'code' => 'UG'],
                ['name' => 'Ukrajina', 'code' => 'UA'],
                ['name' => 'Uruguaj', 'code' => 'UY'],
                ['name' => 'Uzbekistan', 'code' => 'UZ'],
                ['name' => 'Vanuatu', 'code' => 'VU'],
                ['name' => 'Vatikán', 'code' => 'VA'],
                ['name' => 'Venezuela', 'code' => 'VE'],
                ['name' => 'Vietnam', 'code' => 'VN'],
                ['name' => 'Východný Timor', 'code' => 'TL'],
                ['name' => 'Zambia', 'code' => 'ZM'],
                ['name' => 'Západná Sahara', 'code' => 'EH'],
                ['name' => 'Zimbabwe', 'code' => 'ZW'],
            ]);
    }
}
